version: "3.3"

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:7.3.6
    ports:
      - 3000:3000
    env_file: ./.env.grafana
    volumes:
      - ./data/grafana:/var/lib/grafana
    depends_on:
      - loki

  loki:
    container_name: loki
    image: grafana/loki:2.1.0
    ports:
      - 3100:3100

  promtail:
    container_name: promtail
    image: grafana/promtail:2.1.0
    ports:
      - 9080:9080
    command:
      - "--config.file=/etc/promtail/promtail.yml"
    volumes:
      - ./promtail.yml:/etc/promtail/promtail.yml
      - ../../logs:/var/log/app