version: '3'

services:
  inventory: 
    build: 
      context: ./services/inventory
    command: npm start
    networks:
      - dev_network
    ports:
      - "3002:3000"
    volumes:
      - ./logs:/var/log/app:rw
    env_file:
      - ./services/inventory/ci.env
    depends_on:
      - db
  # Common Resource
  db:
    build:
      context: ./deployment-manifests/postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_pass
      TZ: UTC
    networks:
      - dev_network
  
  promtail:
    image: grafana/promtail:2.1.0
    ports:
      - 9080:9080
    command:
      - "--config.file=/etc/promtail/promtail.yml"
    volumes:
      - ./deployment-manifests/grafana-loki/promtail.yml:/etc/promtail/promtail.yml
      - ./logs:/var/log/app
      
networks:
  dev_network:
    driver: bridge